/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chat {
  'id' : ChatId,
  'participants' : Array<User>,
  'messages' : Array<Message>,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : User,
  'lastMessage' : [] | [Message],
  'chatType' : ChatType,
}
export type ChatId = number;
export type ChatType = { 'group' : null } |
  { 'direct' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : User,
  'timestamp' : Time,
}
export type MessageId = number;
export interface MessageInput { 'content' : string, 'chatId' : ChatId }
export type Time = bigint;
export interface User {
  'principal' : Principal,
  'username' : string,
  'name' : string,
}
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDirectChat' : ActorMethod<[Principal], Chat>,
  'createGroupChat' : ActorMethod<[string, Array<Principal>], Chat>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'getAvatarImage' : ActorMethod<[Principal], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChat' : ActorMethod<[ChatId], Chat>,
  'getMyChats' : ActorMethod<[], Array<Chat>>,
  'getMyUser' : ActorMethod<[], User>,
  'getUser' : ActorMethod<[Principal], User>,
  'getUserByUsername' : ActorMethod<[string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string], User>,
  'removeMyAvatarImage' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string, bigint], Array<User>>,
  'sendMessage' : ActorMethod<[MessageInput], Message>,
  'setMyAvatarImage' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];