/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatId = IDL.Nat32;
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const MessageId = IDL.Nat32;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : User,
  'timestamp' : Time,
});
export const ChatType = IDL.Variant({
  'group' : IDL.Null,
  'direct' : IDL.Null,
});
export const Chat = IDL.Record({
  'id' : ChatId,
  'participants' : IDL.Vec(User),
  'messages' : IDL.Vec(Message),
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : User,
  'lastMessage' : IDL.Opt(Message),
  'chatType' : ChatType,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'chatId' : ChatId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDirectChat' : IDL.Func([IDL.Principal], [Chat], []),
  'createGroupChat' : IDL.Func([IDL.Text, IDL.Vec(IDL.Principal)], [Chat], []),
  'deleteAccount' : IDL.Func([], [], []),
  'getAvatarImage' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChat' : IDL.Func([ChatId], [Chat], ['query']),
  'getMyChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
  'getMyUser' : IDL.Func([], [User], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'removeMyAvatarImage' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(User)], ['query']),
  'sendMessage' : IDL.Func([MessageInput], [Message], []),
  'setMyAvatarImage' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatId = IDL.Nat32;
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'name' : IDL.Text,
  });
  const MessageId = IDL.Nat32;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : User,
    'timestamp' : Time,
  });
  const ChatType = IDL.Variant({ 'group' : IDL.Null, 'direct' : IDL.Null });
  const Chat = IDL.Record({
    'id' : ChatId,
    'participants' : IDL.Vec(User),
    'messages' : IDL.Vec(Message),
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : User,
    'lastMessage' : IDL.Opt(Message),
    'chatType' : ChatType,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const MessageInput = IDL.Record({ 'content' : IDL.Text, 'chatId' : ChatId });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDirectChat' : IDL.Func([IDL.Principal], [Chat], []),
    'createGroupChat' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal)],
        [Chat],
        [],
      ),
    'deleteAccount' : IDL.Func([], [], []),
    'getAvatarImage' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChat' : IDL.Func([ChatId], [Chat], ['query']),
    'getMyChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
    'getMyUser' : IDL.Func([], [User], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserByUsername' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'removeMyAvatarImage' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(User)], ['query']),
    'sendMessage' : IDL.Func([MessageInput], [Message], []),
    'setMyAvatarImage' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };